### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by fu**

### CODE REVIEW

**Comment by mobiusklein** [comment]
There is no run-time dependence on Cython. Only to build from source. When building a distribution (sdist/bdist) Cython compiles the .pyx file into a .cpp file which is included in the distribution. For an sdist, setuptools will invoke the C++ compiler for the user and compile the extension module there. For a bdist (e.g. a wheel) the build system will invoke the C++ compiler and build the extension module and include it in the distribution so the user won't need to compile it themselves.

**Comment by fu** [comment]
the pynumpress.cpp file is in .gitignore thus installation fails without cython in requirements

**Comment by mobiusklein** [comment]
That's because it's an artifact of the build process, but installing from a distribution (what would be uploaded to PyPI) the user won't need Cython. You're trying to install from source which is usually a different process, where fewer assumptions are made. Some projects list the libraries needed to build from source in a file named something like "requirements-dev.txt", but the build system isn't aware of this convention.

It's considered bad practice to check in build artifacts since they are usually specific to the local machine (processor architecture, compiler version, OS version). This includes the generated C and C++ code from Cython, which may be modified by different Cython arguments like turning on debugging and tracing code during the compilation step.

**Comment by mobiusklein** [comment]
I'll make a note in the README that to build from source you need to install a recent version of Cython.

**Pull request closed without merging**
